### ISSUE TITLE
Criar unittest para o script sort.py

### ISSUE THREAD

**Issue by leogregianin** [leogregianin/empresas-de-software-mato-grosso#15]

**Comment by enieber** [comment]
O que é necessario para criar um teste unitario?

**Comment by leogregianin** [comment]
@enieber, temos que seguir o que a linguagem dispõe e adaptar o sort.py, por exemplo:
https://docs.python.org/3/library/unittest.html
https://docs.python.org/3/library/unittest.mock.html
