### ISSUE TITLE
gerar um json dos dados

### ISSUE THREAD

**Issue by enieber** [leogregianin/empresas-de-software-mato-grosso#19]
Seria possivel gerar um json dos dodos como 

- [city_usage](https://github.com/leogregianin/empresas-de-software-mato-grosso/blob/master/city_usage.md)

- [cloud_usage](https://github.com/leogregianin/empresas-de-software-mato-grosso/blob/master/cloud_usage.md)

- [database_usage](https://github.com/leogregianin/empresas-de-software-mato-grosso/blob/master/database_usage.md)

- [technology_usage](https://github.com/leogregianin/empresas-de-software-mato-grosso/blob/master/technology_usage.md)

assim daria para fazer front-end consumir esses json e criar um algoritimo de busca e filtragem de empresas de software de mato grosso.

**Comment by leogregianin** [comment]
Olá @enieber, seria legal fazer isso sim. Está na lista de To-Do.

**Comment by leogregianin** [comment]
Url para consumir: https://raw.githubusercontent.com/leogregianin/empresas-de-software-mato-grosso/master/json/empresas.json
