### ISSUE TITLE
build automatico

### ISSUE THREAD

**Issue by enieber** [leogregianin/empresas-de-software-mato-grosso#20]
Vi que vc esta usando travis para fazer testes, não sei se ja esta fazendo, mas seria interessante gerar os novos arquivos `.md` e `.json`(sugerido na issue #19) automaticamente...

**Comment by leogregianin** [comment]
Fazer com que o sort.py gere um arquivo json --> `https://raw.githubusercontent.com/leogregianin/empresas-de-software-mato-grosso/master/mt.json` para os frontends consumirem.
