### ISSUE TITLE
Demais áreas

### ISSUE THREAD

**Issue by CoderSquirrel** [leogregianin/empresas-de-software-mato-grosso#33]
Olá, gostaria de saber o que vocês acham de adicionar demais áreas, além do desenvolvimento, nas empresas de software, como por exemplo UI, UX, B.I. ou Analise de dados entre outra.
Até mais

**Comment by leogregianin** [comment]
Olá @CoderSquirrel, o que estiver envolvido com tecnologia pode entrar na lista sem problemas.
