### ISSUE TITLE
Objetivo dos registros.

### ISSUE THREAD

**Issue by jackmakiyama** [leogregianin/empresas-de-software-mato-grosso#6]
Olá qual seria o objetivo dos registros?

Parece ser direcionado para software house, mas parece também que é para qualquer empresa que desenvolve software internalizado.

Fiz uma [PR](https://github.com/leogregianin/empresas-de-software-mato-grosso/pull/5), mas não somos uma software house, desenvolvemos nosso próprio software.

Talvez esclarecendo isso seria legal algum direcionamento intencional no README tipo um guia para pedir apoios para eventos, procurar trabalho ou mesmo boicotes(espero que isso nunca aconteça).

Abraços. o/

**Comment by leogregianin** [comment]
@jackmakiyama, sua ideia é ótima em incluir uma informação mais clara quanto ao objetivo. A ideia é ser uma lista genérica, levantar todas as empresas que desenvolvem software, aplicativos e sites independente se desenvolvem internamente ou vendem software, por exemplo, tem várias startups como Dropo, AgroV, Estuda.com ou órgãos públicos nessa lista.

**Comment by leogregianin** [comment]
Melhorei o README, ficou mais claro :D
